package edu.eci.arsw.collabboard.application.service;

import edu.eci.arsw.collabboard.application.exception.BoardNotFoundException;
import edu.eci.arsw.collabboard.application.port.out.BoardRepository;
import edu.eci.arsw.collabboard.domain.model.Board;
import edu.eci.arsw.collabboard.domain.model.BoardElement;
import org.springframework.stereotype.Service;

import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.UUID;

/**
 * Use cases of the collaborative board.
 *
 * <p>This service owns the application rules (identity generation, existence
 * checks, element consistency) and depends only on the {@link BoardRepository}
 * port, never on a concrete persistence technology. The dependency arrives by
 * constructor injection so the service can be unit tested with any adapter.</p>
 */
@Service
public class BoardApplicationService {

    private final BoardRepository repository;

    public BoardApplicationService(BoardRepository repository) {
        this.repository = repository;
    }

    /**
     * Creates a board with a server-generated identity and no elements.
     *
     * <p>The id is generated here, not received from the client: identity is an
     * application concern, and letting the caller choose it would allow
     * silently overwriting an existing board through the create use case.</p>
     *
     * @throws IllegalArgumentException if the name is null or blank
     */
    public Board createBoard(String name) {
        Board board = new Board(UUID.randomUUID().toString(), name, List.of());
        return repository.save(board);
    }

    /**
     * @throws BoardNotFoundException if no board is stored under that id
     */
    public Board getBoard(String boardId) {
        return repository.findById(boardId)
                .orElseThrow(() -> new BoardNotFoundException(boardId));
    }

    /**
     * Replaces the whole content of an existing board, keeping its identity.
     *
     * <p>This is a replace, not an upsert: a PUT over an unknown id is a client
     * error, because ids are generated by the create use case and an unknown id
     * means the caller is addressing a board that never existed or was lost.</p>
     *
     * @throws BoardNotFoundException   if the board does not exist
     * @throws IllegalArgumentException if the name is invalid or two elements
     *                                  share the same id
     */
    public Board replaceBoard(String boardId, String name, List<BoardElement> elements) {
        Board existing = getBoard(boardId);
        List<BoardElement> newElements = elements == null ? List.of() : elements;
        rejectDuplicateElementIds(newElements);

        return repository.save(new Board(existing.id(), name, newElements));
    }

    /**
     * Element ids must be unique inside a board: they are the handle the future
     * interactive client will use to move or edit a single shape, so duplicates
     * would make that operation ambiguous.
     */
    private void rejectDuplicateElementIds(List<BoardElement> elements) {
        Set<String> seen = new HashSet<>();
        for (BoardElement element : elements) {
            if (element == null) {
                throw new IllegalArgumentException("Elements cannot contain null entries");
            }
            if (!seen.add(element.id())) {
                throw new IllegalArgumentException("Duplicated element id: " + element.id());
            }
        }
    }
}
